spring.application.name=auth-service
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/service_on_wheels

jwt.secret=ServiceOnWheels_SuperSecret_JWT_Key_2024_ChangeInProd!
jwt.expiration=86400000

logging.level.com.serviceonwheels=DEBUG
logging.level.org.springframework.security=INFO
